services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: puppamilafava

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  web:
    image: hello_world:1.0
    restart: always
    ports:
      - "4000:4000"
    environment:
      SECRET_KEY_BASE: 't46dvBqYRyMgmI+i6lKJvRfZ+nDrgCWJvnaAbaNj1J34PCgRYLP+pABfz28EjWDU'
      DATABASE_URL: 'ecto://postgres:example@db:5432/puppamilafava'
      DB_HOST: 'db'
    depends_on:
      - db